name: CI-Lobby

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: '**'
    
env:
  AWS_REGION: us-east-1
  
  
# jobs:
#   lint:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Clone repo...
#       uses: actions/checkout@v2
#     - name: Installing node...
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'
#     - name: change file
#       run: | 
#         echo "my secret is ${{ secrets.HELLO }}"
#         mv commands.txt commands2.txt
#         sed -i "s~index~${{ secrets.HELLO }}~" commands2.txt
#         cat commands2.txt
#     - name: Ls files
#       run: ls
#     - name: Running linters...
#       run: |
#         npm i
#        npm run lint

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Pull and Push to ECR
      run: |
        docker pull hello-world
        docker tag hello-world:latest public.ecr.aws/n2n4a4x9/lobby:hello-world
        docker push public.ecr.aws/n2n4a4x9/lobby:hello-world
